-- 0006_seed_backlog.sql — 150 curated concept titles.
--
-- The syllabus, not the lessons. Gemini turns each of these into a written
-- concept in Phase 6; curating the titles is what makes deduplication trivial
-- and keeps the subject matter deliberate rather than whatever the model
-- happens to favour. Roughly 30 per topic, about six months of
-- daily learning before the catalog needs extending.

begin;

insert into public.concept_backlog (slug, topic_id, title, angle, difficulty)
select v.slug, t.id, v.title, v.angle, v.difficulty
from (values
  ('backpropagation', 'artificial-intelligence', 'Backpropagation', 'how the gradient actually reaches every weight', 2),
  ('transformers', 'artificial-intelligence', 'Transformers', 'why attention replaced recurrence', 2),
  ('tokenization', 'artificial-intelligence', 'Tokenization', 'why models see fragments, not words', 1),
  ('fine-tuning', 'artificial-intelligence', 'Fine-tuning', 'adapting a pretrained model to a narrow task', 2),
  ('transfer-learning', 'artificial-intelligence', 'Transfer Learning', 'why starting from someone else''s weights works', 1),
  ('regularization', 'artificial-intelligence', 'Regularization', 'penalising complexity to survive new data', 2),
  ('dropout', 'artificial-intelligence', 'Dropout', 'training a crowd of smaller networks at once', 2),
  ('batch-normalization', 'artificial-intelligence', 'Batch Normalization', 'keeping activations in a sane range', 3),
  ('activation-functions', 'artificial-intelligence', 'Activation Functions', 'why a network without them is just a matrix', 1),
  ('loss-functions', 'artificial-intelligence', 'Loss Functions', 'how you tell a model what wrong means', 1),
  ('convolutional-neural-networks', 'artificial-intelligence', 'Convolutional Neural Networks', 'exploiting the fact that pixels have neighbours', 2),
  ('recurrent-neural-networks', 'artificial-intelligence', 'Recurrent Neural Networks', 'carrying state through a sequence', 2),
  ('reinforcement-learning', 'artificial-intelligence', 'Reinforcement Learning', 'learning from consequences rather than answers', 2),
  ('q-learning', 'artificial-intelligence', 'Q-Learning', 'estimating the value of an action', 3),
  ('supervised-vs-unsupervised-learning', 'artificial-intelligence', 'Supervised vs Unsupervised Learning', 'with labels and without', 1),
  ('clustering', 'artificial-intelligence', 'Clustering', 'structure without a teacher', 1),
  ('dimensionality-reduction', 'artificial-intelligence', 'Dimensionality Reduction', 'fewer numbers, same meaning', 2),
  ('principal-component-analysis', 'artificial-intelligence', 'Principal Component Analysis', 'finding the directions that carry variance', 3),
  ('bias-and-variance', 'artificial-intelligence', 'Bias and Variance', 'the two ways a model can be wrong', 2),
  ('cross-validation', 'artificial-intelligence', 'Cross-Validation', 'honest evaluation when data is scarce', 1),
  ('confusion-matrix', 'artificial-intelligence', 'Confusion Matrix', 'why accuracy alone misleads', 1),
  ('precision-and-recall', 'artificial-intelligence', 'Precision and Recall', 'the trade-off behind every classifier', 2),
  ('hallucination-in-language-models', 'artificial-intelligence', 'Hallucination in Language Models', 'why fluent text can be false', 1),
  ('retrieval-augmented-generation', 'artificial-intelligence', 'Retrieval-Augmented Generation', 'giving a model something to read first', 2),
  ('prompt-engineering', 'artificial-intelligence', 'Prompt Engineering', 'the input is part of the program', 1),
  ('temperature-and-sampling', 'artificial-intelligence', 'Temperature and Sampling', 'the dial between dull and unhinged', 2),
  ('context-windows', 'artificial-intelligence', 'Context Windows', 'why models forget the start of long inputs', 1),
  ('mixture-of-experts', 'artificial-intelligence', 'Mixture of Experts', 'routing each token to a specialist', 3),
  ('knowledge-distillation', 'artificial-intelligence', 'Knowledge Distillation', 'a small model taught by a large one', 3),
  ('diffusion-models', 'artificial-intelligence', 'Diffusion Models', 'generating by removing noise', 3),
  ('acid-transactions', 'software-engineering', 'ACID Transactions', 'the four guarantees behind a reliable write', 2),
  ('cap-theorem', 'software-engineering', 'CAP Theorem', 'what you give up when the network splits', 3),
  ('eventual-consistency', 'software-engineering', 'Eventual Consistency', 'correct later, available now', 2),
  ('message-queues', 'software-engineering', 'Message Queues', 'decoupling producers from consumers', 2),
  ('load-balancing', 'software-engineering', 'Load Balancing', 'spreading work without hot spots', 1),
  ('rate-limiting', 'software-engineering', 'Rate Limiting', 'protecting a service from its own users', 2),
  ('circuit-breakers', 'software-engineering', 'Circuit Breakers', 'failing fast instead of piling up', 2),
  ('retries-and-backoff', 'software-engineering', 'Retries and Backoff', 'why naive retries make outages worse', 2),
  ('dependency-injection', 'software-engineering', 'Dependency Injection', 'handing collaborators in rather than reaching out', 2),
  ('test-doubles', 'software-engineering', 'Test Doubles', 'fakes, stubs, mocks, and when each fits', 2),
  ('continuous-integration', 'software-engineering', 'Continuous Integration', 'merging small and often', 1),
  ('feature-flags', 'software-engineering', 'Feature Flags', 'shipping code before shipping behaviour', 2),
  ('blue-green-deployment', 'software-engineering', 'Blue-Green Deployment', 'swapping environments instead of upgrading in place', 2),
  ('database-migrations', 'software-engineering', 'Database Migrations', 'changing schema without losing data', 2),
  ('normalization', 'software-engineering', 'Normalization', 'storing each fact exactly once', 2),
  ('denormalization', 'software-engineering', 'Denormalization', 'trading duplication for read speed', 2),
  ('n-1-query-problem', 'software-engineering', 'N+1 Query Problem', 'the loop that quietly makes a thousand queries', 2),
  ('connection-pooling', 'software-engineering', 'Connection Pooling', 'reusing expensive handshakes', 2),
  ('optimistic-locking', 'software-engineering', 'Optimistic Locking', 'detecting conflicts instead of preventing them', 3),
  ('pessimistic-locking', 'software-engineering', 'Pessimistic Locking', 'holding the row while you work', 3),
  ('webhooks', 'software-engineering', 'Webhooks', 'letting the server call you back', 1),
  ('graphql', 'software-engineering', 'GraphQL', 'asking for exactly the fields you need', 2),
  ('grpc', 'software-engineering', 'gRPC', 'typed contracts over HTTP/2', 2),
  ('content-delivery-networks', 'software-engineering', 'Content Delivery Networks', 'moving bytes closer to people', 1),
  ('cache-invalidation', 'software-engineering', 'Cache Invalidation', 'the genuinely hard part', 2),
  ('observability', 'software-engineering', 'Observability', 'logs, metrics, and traces', 2),
  ('structured-logging', 'software-engineering', 'Structured Logging', 'logs a machine can query', 1),
  ('semantic-versioning', 'software-engineering', 'Semantic Versioning', 'what a version number promises', 1),
  ('technical-debt', 'software-engineering', 'Technical Debt', 'borrowing speed against future effort', 1),
  ('code-review', 'software-engineering', 'Code Review', 'what it catches that tests cannot', 1),
  ('binary-search', 'computer-science', 'Binary Search', 'halving the problem every step', 1),
  ('sorting-algorithms', 'computer-science', 'Sorting Algorithms', 'why there is no single best one', 2),
  ('quicksort', 'computer-science', 'Quicksort', 'partitioning around a pivot', 2),
  ('merge-sort', 'computer-science', 'Merge Sort', 'divide, conquer, and combine', 2),
  ('linked-lists', 'computer-science', 'Linked Lists', 'pointers instead of contiguity', 1),
  ('stacks-and-queues', 'computer-science', 'Stacks and Queues', 'the two disciplines of ordering', 1),
  ('binary-search-trees', 'computer-science', 'Binary Search Trees', 'keeping order while you insert', 2),
  ('balanced-trees', 'computer-science', 'Balanced Trees', 'why an unbalanced tree degrades to a list', 3),
  ('heaps', 'computer-science', 'Heaps', 'always knowing the smallest item', 2),
  ('graphs', 'computer-science', 'Graphs', 'modelling relationships rather than sequences', 2),
  ('breadth-first-search', 'computer-science', 'Breadth-First Search', 'exploring in rings', 2),
  ('depth-first-search', 'computer-science', 'Depth-First Search', 'following one path to the end', 2),
  ('dijkstras-algorithm', 'computer-science', 'Dijkstra''s Algorithm', 'shortest paths with weights', 3),
  ('dynamic-programming', 'computer-science', 'Dynamic Programming', 'remembering subproblems you have solved', 3),
  ('memoization', 'computer-science', 'Memoization', 'caching a function against itself', 2),
  ('greedy-algorithms', 'computer-science', 'Greedy Algorithms', 'when local choices are globally right', 2),
  ('time-and-space-trade-offs', 'computer-science', 'Time and Space Trade-offs', 'buying speed with memory', 1),
  ('amortized-analysis', 'computer-science', 'Amortized Analysis', 'why an occasional expensive step is still cheap', 3),
  ('pointers-and-references', 'computer-science', 'Pointers and References', 'names for places', 1),
  ('garbage-collection', 'computer-science', 'Garbage Collection', 'who frees the memory you forgot', 2),
  ('stack-and-heap-memory', 'computer-science', 'Stack and Heap Memory', 'two lifetimes, two costs', 2),
  ('virtual-memory', 'computer-science', 'Virtual Memory', 'the illusion of unlimited address space', 3),
  ('paging', 'computer-science', 'Paging', 'swapping memory in fixed-size pages', 3),
  ('context-switching', 'computer-science', 'Context Switching', 'the cost of pretending to do many things', 2),
  ('threads-vs-processes', 'computer-science', 'Threads vs Processes', 'shared memory or isolation', 2),
  ('race-conditions', 'computer-science', 'Race Conditions', 'when timing decides correctness', 2),
  ('mutexes-and-semaphores', 'computer-science', 'Mutexes and Semaphores', 'taking turns, safely', 2),
  ('the-tcp-handshake', 'computer-science', 'The TCP Handshake', 'how a connection agrees to exist', 2),
  ('dns-resolution', 'computer-science', 'DNS Resolution', 'turning names into addresses', 1),
  ('public-key-cryptography', 'computer-science', 'Public Key Cryptography', 'a lock anyone can close and only you can open', 2),
  ('vectors', 'mathematics', 'Vectors', 'magnitude and direction as one object', 1),
  ('matrices', 'mathematics', 'Matrices', 'a table that transforms space', 1),
  ('matrix-multiplication', 'mathematics', 'Matrix Multiplication', 'composing two transformations', 2),
  ('determinants', 'mathematics', 'Determinants', 'how much a transformation stretches space', 3),
  ('eigenvectors-and-eigenvalues', 'mathematics', 'Eigenvectors and Eigenvalues', 'directions a transformation only scales', 3),
  ('dot-product', 'mathematics', 'Dot Product', 'measuring alignment between vectors', 1),
  ('cross-product', 'mathematics', 'Cross Product', 'a vector perpendicular to two others', 2),
  ('vector-spaces', 'mathematics', 'Vector Spaces', 'the rules any space of vectors obeys', 2),
  ('derivatives', 'mathematics', 'Derivatives', 'the rate of change at an instant', 1),
  ('the-chain-rule', 'mathematics', 'The Chain Rule', 'differentiating a function of a function', 2),
  ('partial-derivatives', 'mathematics', 'Partial Derivatives', 'changing one variable at a time', 2),
  ('gradients', 'mathematics', 'Gradients', 'the direction of steepest ascent', 2),
  ('integrals', 'mathematics', 'Integrals', 'accumulating change into a total', 1),
  ('limits', 'mathematics', 'Limits', 'getting arbitrarily close', 2),
  ('conditional-probability', 'mathematics', 'Conditional Probability', 'how one fact reshapes another', 1),
  ('independence', 'mathematics', 'Independence', 'when knowing one thing tells you nothing', 1),
  ('random-variables', 'mathematics', 'Random Variables', 'putting numbers on uncertainty', 1),
  ('variance-and-standard-deviation', 'mathematics', 'Variance and Standard Deviation', 'how spread out the outcomes are', 1),
  ('the-normal-distribution', 'mathematics', 'The Normal Distribution', 'why so much data looks like a bell', 1),
  ('the-central-limit-theorem', 'mathematics', 'The Central Limit Theorem', 'why averages become normal', 3),
  ('the-law-of-large-numbers', 'mathematics', 'The Law of Large Numbers', 'why long runs converge', 2),
  ('hypothesis-testing', 'mathematics', 'Hypothesis Testing', 'deciding whether an effect is real', 2),
  ('p-values', 'mathematics', 'p-values', 'what they do and do not tell you', 2),
  ('confidence-intervals', 'mathematics', 'Confidence Intervals', 'an estimate with its uncertainty attached', 2),
  ('correlation-vs-causation', 'mathematics', 'Correlation vs Causation', 'the most expensive confusion in data', 1),
  ('regression', 'mathematics', 'Regression', 'fitting a line through evidence', 2),
  ('logarithms', 'mathematics', 'Logarithms', 'turning multiplication into addition', 1),
  ('modular-arithmetic', 'mathematics', 'Modular Arithmetic', 'counting that wraps around', 2),
  ('combinatorics', 'mathematics', 'Combinatorics', 'counting without enumerating', 2),
  ('graph-theory', 'mathematics', 'Graph Theory', 'the mathematics of connection', 2),
  ('the-shell', 'linux-systems', 'The Shell', 'a programming language for your machine', 1),
  ('pipes-and-redirection', 'linux-systems', 'Pipes and Redirection', 'composing small programs', 1),
  ('standard-streams', 'linux-systems', 'Standard Streams', 'stdin, stdout, and stderr', 1),
  ('exit-codes', 'linux-systems', 'Exit Codes', 'how programs report success', 1),
  ('environment-variables', 'linux-systems', 'Environment Variables', 'configuration a process inherits', 1),
  ('file-permissions', 'linux-systems', 'File Permissions', 'read, write, execute, for whom', 1),
  ('users-and-groups', 'linux-systems', 'Users and Groups', 'identity on a multi-user system', 1),
  ('sudo-and-privilege', 'linux-systems', 'sudo and Privilege', 'borrowing authority deliberately', 1),
  ('the-filesystem-hierarchy', 'linux-systems', 'The Filesystem Hierarchy', 'why everything lives where it does', 1),
  ('inodes', 'linux-systems', 'Inodes', 'the file behind the filename', 2),
  ('hard-and-symbolic-links', 'linux-systems', 'Hard and Symbolic Links', 'two ways to point at data', 2),
  ('mounting', 'linux-systems', 'Mounting', 'grafting a filesystem into the tree', 2),
  ('signals', 'linux-systems', 'Signals', 'interrupting a running process', 2),
  ('exit-and-zombie-processes', 'linux-systems', 'Exit and Zombie Processes', 'children the parent never collected', 2),
  ('cron', 'linux-systems', 'Cron', 'scheduling work by the clock', 1),
  ('package-managers', 'linux-systems', 'Package Managers', 'dependency resolution as a service', 1),
  ('shared-libraries', 'linux-systems', 'Shared Libraries', 'code loaded once, used by many', 2),
  ('static-vs-dynamic-linking', 'linux-systems', 'Static vs Dynamic Linking', 'bundling or borrowing', 2),
  ('system-calls', 'linux-systems', 'System Calls', 'the boundary between your code and the kernel', 2),
  ('kernel-vs-user-space', 'linux-systems', 'Kernel vs User Space', 'why the separation exists', 2),
  ('the-page-cache', 'linux-systems', 'The Page Cache', 'why the second read is instant', 2),
  ('load-average', 'linux-systems', 'Load Average', 'what those three numbers actually mean', 2),
  ('oom-killer', 'linux-systems', 'OOM Killer', 'who dies when memory runs out', 2),
  ('namespaces', 'linux-systems', 'Namespaces', 'the isolation containers are built from', 3),
  ('cgroups', 'linux-systems', 'cgroups', 'capping what a process may consume', 3),
  ('containers', 'linux-systems', 'Containers', 'a process with a different view of the world', 2),
  ('sockets', 'linux-systems', 'Sockets', 'endpoints for talking over a network', 2),
  ('ports-and-binding', 'linux-systems', 'Ports and Binding', 'why only one process gets 8080', 1),
  ('iptables-and-firewalls', 'linux-systems', 'iptables and Firewalls', 'deciding which packets live', 3),
  ('logs-and-journald', 'linux-systems', 'Logs and journald', 'where a system records what happened', 1)
) as v (slug, topic_slug, title, angle, difficulty)
join public.topics t on t.slug = v.topic_slug
-- Skip anything already published as a seed concept.
where not exists (select 1 from public.concepts c where c.slug = v.slug)
on conflict (slug) do nothing;

commit;
